import Head from 'next/head'
import Navbar from '../components/navbar'
import Hero from '../components/hero'
import About from '../components/about'
import Content from '../components/contents'
import Footer from '../components/footer'
import Premium from '../components/premium'
import HomeNumber from "../components/homenumber"
import Meta from '../components/meta'
import Chat from '../components/chat'
import Image from "next/image";
import VoiceAlanAi from '../components/voiceAlanAi'
export default function Home() {
  return (
    <div>
      <Head>
        <title>TALKING MINDS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      {/* <HomeNumber /> */}
      <Content />
      <Premium />
      <Meta />
      <Footer />
      <Chat />
      <VoiceAlanAi />
    </div>
  )
}
